export interface Presence {
	groups: any[];
	id: string;
	instance: string;
	instanceType: string;
	platform: string;
	status: string;
	travelingToInstance: string;
	travelingToWorld: string;
	world: string;
}

export interface UserData {
	acceptedPrivacyVersion: number;
	acceptedTOSVersion: number;
	accountDeletionDate: string | null;
	accountDeletionLog: string | null;
	activeFriends: string[];
	allowAvatarCopying: boolean;
	badges: string[];
	bio: string;
	bioLinks: string[];
	currentAvatar: string;
	currentAvatarAssetUrl: string;
	currentAvatarImageUrl: string;
	currentAvatarTags: string[];
	currentAvatarThumbnailImageUrl: string;
	date_joined: string;
	developerType: string;
	displayName: string;
	emailVerified: boolean;
	fallbackAvatar: string;
	friendGroupNames: string[];
	friendKey: string;
	friends: string[];
	googleDetails: object;
	googleId: string;
	hasBirthday: boolean;
	hasEmail: boolean;
	hasLoggedInFromClient: boolean;
	hasPendingEmail: boolean;
	hideContentFilterSettings: boolean;
	homeLocation: string;
	id: string;
	isBoopingEnabled: boolean;
	isFriend: boolean;
	last_activity: string;
	last_login: string;
	last_mobile: string | null;
	last_platform: string;
	obfuscatedEmail: string;
	obfuscatedPendingEmail: string;
	oculusId: string;
	offlineFriends: string[];
	onlineFriends: string[];
	pastDisplayNames: string[];
	picoId: string;
	presence: Presence;
	profilePicOverride: string;
	profilePicOverrideThumbnail: string;
	pronouns: string;
	state: string;
	status: string;
	statusDescription: string;
	statusFirstTime: boolean;
	statusHistory: string[];
	steamDetails: object;
	steamId: string;
	tags: string[];
	twoFactorAuthEnabled: boolean;
	twoFactorAuthEnabledDate: string | null;
	unsubscribe: boolean;
	updated_at: string;
	userIcon: string;
	userLanguage: string | null;
	userLanguageCode: string | null;
	username: string;
	viveId: string;
}
